export default {
  root: "email-editor-root",
  paragraph: "email-editor-paragraph",
  textBlock: "email-editor-text-block",
  text: {
    bold: 'email-editor-text-bold',
    code: 'email-editor-text-code',
    hashtag: 'email-editor-text-hashtag',
    italic: 'email-editor-text-italic',
    overflowed: 'email-editor-text-overflowed',
    strikethrough: 'email-editor-text-strikethrough',
    underline: 'email-editor-text-underline',
    underlineStrikethrough: 'email-editor-text-underlineStrikethrough',
    subscript: 'email-editor-text-subscript',
    superscript: 'email-editor-text-superscript',
  },
  link: 'email-editor-link',
  image: 'email-editor-image',
  imageBlock: 'email-editor-image-block',
  emailTemplateRoot: 'email-editor-email-template-root',
  emailTemplateBlock: 'email-editor-email-template-block',
  layoutContainer: 'email-editor-layout-container',
  layoutItem: 'email-editor-layout-item',
  buttonLink: 'email-editor-button-link',
  buttonLinkBlock: 'email-editor-button-link-block',
}